makedeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from restframework import views
from rest_framework.documentation import include_docs_urls
from rest_framework.authtoken import views


router = routers.DefaultRouter()

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('',include('product.urls')),
    path('',include('purchase.urls')),
    path('',include('notifications.urls')),
    path('', include('social_django.urls', namespace='social')),

    path('api/auth/', include('knox.urls')),
    path('api/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token, name='api-tokn-auth'),
    path('api-auth/', include('rest_framework.urls')),
    path('',include('restframework.urls')),
    path('docs/', include_docs_urls(title='Todo Api')),
    
    
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

product/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import DeleteProductView, EditProductView, ProducView, ProductCreateView, MyProductView, acceptpurchase, mark_sold, mark_unsold,rejectpurchase
urlpatterns = [
    path('createproduct',ProductCreateView.as_view(), name='createproduct'),
    path('myproducts', MyProductView.as_view(), name= 'myproducts'),
    path('product/<int:id>/', ProducView.as_view(), name= 'product'),
    path('editproduct/<int:id>/', EditProductView.as_view(), name= 'editproduct'),
    path('<pk>/acceptpurchase/', acceptpurchase, name= 'acceptpurchase'),
    path('<pk>/rejectpurchase/', rejectpurchase, name= 'rejectpurchase'),
    path('<pk>/deleteproduct/', DeleteProductView.as_view(), name='deleteproduct'),
    path('<pk>/marksold/', mark_sold, name='marksold'),
    path('<pk>/mark-unsold/', mark_unsold, name='markunsold'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User

class ProductCategory(models.Model):
    category = models.CharField( max_length=50)

    def __str__(self):
        return self.category


class Product(models.Model):
    user = models.ForeignKey(User, verbose_name='', on_delete=models.CASCADE)
    name = models.CharField( max_length=50)
    description = models.TextField()
    category = models.ForeignKey(ProductCategory, verbose_name='Category', on_delete=models.CASCADE)
    location = models.CharField( max_length=50, null=True, blank=True)
    image1 = models.ImageField( upload_to= 'images', height_field=None, width_field=None, max_length=None)
    image2 = models.ImageField( upload_to= 'images', height_field=None, width_field=None, max_length=None, null=True, blank=True)
    image3 = models.ImageField( upload_to= 'images', height_field=None, width_field=None, max_length=None, null=True, blank=True)
    image4 = models.ImageField( upload_to= 'images', height_field=None, width_field=None, max_length=None, null=True, blank=True)
    price = models.IntegerField()
    time_to_publish = models.TimeField( auto_now= False, auto_now_add= True, null=True, blank=True)
    is_sold = models.BooleanField(default=False)

    def __str__(self):
        return self.name

purchase/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product

class Purchase(models.Model):
    seller = models.ForeignKey(User, verbose_name=(""), on_delete=models.CASCADE, related_name= 'seller')
    buyer = models.ForeignKey(User, verbose_name=(""), on_delete=models.CASCADE, related_name='buyer')
    product = models.ForeignKey(Product, verbose_name=(""), on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    buyer_price = models.IntegerField()

    def __str__(self):
        return self.buyer.username

dashboard/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from django.db.models.fields.files import ImageFieldFile
from django.forms.fields import ImageField
from .models import UserDetails
from django.core.exceptions import ValidationError


 
class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields =  ('username', 'email', 'password1','password2')


class UserDetailsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # profile_picture = forms.ImageField(attrs={'class': 'form-control'})

    class Meta:
        profile_picture = forms.ImageField(required=False)
        model = UserDetails
        fields = ('name', 'phone', 'profile_picture')

        

class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ('username', 'email')

product/forms.py
from django import forms
from django.contrib.auth import models
from django.forms import ModelForm
from django.utils.regex_helper import flatten_result
from .models import Product

class CreateProductForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # price = forms.NumberInput(attrs={'class': 'form-control'})
    image2 = forms.ImageField(required=False)
    image3 = forms.ImageField(required=False)
    image4 = forms.ImageField(required=False)
    time_to_publish = forms.TimeField(widget=forms.TimeInput(format='%H:%M'),required=False)

    class Meta:
        model = Product
        fields = "__all__"
        exclude = ['user']

class EditProductForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # price = forms.NumberInput(attrs={'class': 'form-control'})
    image2 = forms.ImageField(required=False)
    image3 = forms.ImageField(required=False)
    image4 = forms.ImageField(required=False)
    time_to_publish = forms.TimeField(widget=forms.TimeInput(format='%H:%M'),required=False)
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ['user']  

product/views.py
from django.http.response import HttpResponse
from dashboard.models import UserDetails
from purchase.models import Purchase
from purchase.forms import BuyForm, PurchaseStatusForm
from django.views.generic.base import TemplateView
from product.models import Product
from notifications.models import BroadcastNotification
from typing import Generic
from django import forms
from django.db import models
from django.shortcuts import render
from django.urls.base import is_valid_path, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import CreateProductForm, EditProductForm
from django.contrib import messages
from django.shortcuts import redirect,get_object_or_404
from django.template.loader import render_to_string
from django.core.mail import EmailMessage, send_mail
from django.conf import settings
from django.contrib.auth.models import User
from twilio.rest import Client
from asgiref.sync import async_to_sync  
import channels.layers
from datetime import datetime  



class ProductCreateView(LoginRequiredMixin, generic.FormView):
    template_name = 'product/createproduct.html'
    form_class = CreateProductForm
    success_url = reverse_lazy('dashboard')
    login_url = '/accounts/login/'

    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST, request.FILES)
            if form.is_valid():
                fm = form.save(commit= False)
                fm.user = request.user
                fm.save()
                messages.success(request,'Product created')
                return redirect('dashboard')
            else:
                messages.success(request,  ' Invalid form   ')
                return render(request, self.template_name, {'form': form})


class MyProductView(LoginRequiredMixin,generic.ListView):
    template_name = 'product/myproducts.html'
    context_object_name = 'products'
    def get_queryset(self):
        return Product.objects.filter(user=self.request.user)


class ProducView(generic.CreateView):
    template_name = 'product/product.html'
    context_object_name = 'products'

    def get (self, request, id):
        # import pdb;
        # pdb.set_trace() 
        product = Product.objects.get(id = id)
        purchase = ''
        buyform = BuyForm
        seller_product = Purchase.objects.filter(product = product, seller = request.user) #checking for myproducts as seller

        if Purchase.objects.filter(product = product, buyer = request.user):    # checking for purchases as buyer
            if Purchase.objects.filter(product = product, buyer = request.user):
                purchase = Purchase.objects.get(product = product, buyer = request.user)
            context= {'product': product, 'purchase': purchase, 'seller_product': seller_product}
        else:
            context= {'product': product, 'buyform': buyform, 'seller_product': seller_product}
        return render(request, self.template_name, context )
    
    def post(self, request, id):
        if request.method == 'POST':
            buyer = request.user
            product = Product.objects.get(id= id)
            seller = product.user
            seller_email = seller.email
            buyform = BuyForm(request.POST)
            price = buyform['buyer_price'].value()
            if buyform.is_valid():
                fm = buyform.save(commit=False)
                fm.seller = seller
                fm.buyer = buyer
                fm.status = False
                fm.product = product
                fm.save()

                #notification
                channel_layer = channels.layers.get_channel_layer()
                async_to_sync(channel_layer.group_send)(    
                    'notification_%s' % seller.username,
                    {
                        'type' : 'send_notification',
                        'message' : f'Purchase request from {buyer.username} for {product.name}',
                    }
                )
                notification = BroadcastNotification.objects.create(message= f'Purchase request from {buyer.username} for {product.name}', sent= True, to= seller )
                notification.save()

                # sending mail
                # mail_subject = 'Product purchase notification.'
                # message = render_to_string('product/emailnotification.html', {
                #     'buyer': request.user,
                #     'product': product.name,
                #     'price' : price,
                #     'seller': seller    
                # })
                # email_from = settings.EMAIL_HOST_USER
                # send_mail( mail_subject, message, email_from, [seller_email] )

                # twilio send sms
                # message_to_broadcast = ("Have you played the incredible TwilioQuest ")
                # client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
                # message = client.messages.create(
                # body=f' Product purchase notification \n Hi {seller} \n User {request.user} wants to buy your product {product.name} for the price Rs{price}.',
                # from_=settings.TWILIO_NUMBER,
                # to=f'+919656073331')

                messages.success(request, 'Purchase request submitted')
                return redirect (self.request.path_info)
            else:
                return render(request, self.template_name, {'buyform': buyform})



class EditProductView(LoginRequiredMixin,generic.CreateView):
    template_name = 'product/editproduct.html'
    form_class = EditProductForm

    def get(self, request, id):
        form = self.form_class
        if request.user.is_authenticated:
            product = Product.objects.get(id = id)
            initial_data = {
                'name' : product.name,
                'description' : product.description,
                'location' : product.location,
                'category' : product.category,
                'image1' : product.image1,
                'image2' : product.image2,
                'image3' : product.image3,
                'image4' : product.image4,
                'price': product.price,
                'time_to_publish' : product.time_to_publish
            }
            form = self.form_class(initial = initial_data)
            context= {'form': form, 'product': product}
            return render(request, self.template_name, context)
        else:
            return redirect('login')
    
    def post(self, request, id):
        if request.method == 'POST':
            # import pdb
            # pdb.set_trace()
            product = Product.objects.get(id=id)
            form = self.form_class(request.POST, request.FILES, instance= product)
            if form.is_valid():
                fs = form.save(commit = False)
                fs.user =request.user
                form.save()
                messages.success(request, 'Product details updated.')
                return redirect('myproducts')
        return render(request, self.template_name, {'form': form})


def acceptpurchase(request, pk):
    purchase = get_object_or_404(Purchase, pk=pk)
    purchase.status = True
    purchase.save(update_fields=['status'])
    seller_email = purchase.seller.email
    print(seller_email)
    mail_subject = 'Product purchase notification.'
    message = render_to_string('product/sellconfirm_mail.html', {
        'buyer': request.user,
        'product': purchase.product.name,
        'price' : purchase.buyer_price,
        'seller': purchase.seller
    })
    email_from = settings.EMAIL_HOST_USER
    send_mail( mail_subject, message, email_from, [seller_email] )
    return redirect('myproducts')


def rejectpurchase(request, pk):
    purchase = get_object_or_404(Purchase, pk=pk)
    purchase.status = False
    purchase.save(update_fields=['status'])
    return redirect('myproducts')
    

class DeleteProductView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('myproducts')
    template_name = 'product/deleteconfirm.html'


def mark_sold(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_sold = True
    product.save(update_fields=['is_sold'])
    return redirect ('myproducts')


def mark_unsold(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_sold = False
    product.save(update_fields=['is_sold'])
    return redirect ('myproducts')

product/templates/product/createproduct.html
{% extends 'dashboard/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
</head>

<body >
        <section class="vh-100 " style="background-color: grey;">
          <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
              <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;     margin-bottom: 50px;">
                  <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                      <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
        
                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Add your Product</p>


        
                        <form class="mx-1 mx-md-4" method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
        
                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              {{form.name}}
                              <label class="form-label" for="form3Example1c">Product Name</label>
                            </div>
                          </div>
        
                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              {{form.description}}
                              <label class="form-label" for="form3Example3c">About your productt</label>
                            </div>
                          </div>

                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              {{form.category}}
                              <label class="form-label" for="form3Example3c">Product category</label>
                            </div>
                          </div>
        
                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              {{form.location}}
                              <label class="form-label" for="form3Example4c">Your location</label>
                            </div>
                          </div>
        
                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              <input type="number" class="form-control" name="price" id="id_price">
                              <label class="form-label" for="form3Example4cd">Price of your product</label>
                            </div>
                          </div>
        
                          <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              {{form.time_to_publish}}

                              <label class="form-label" for="form3Example4cd">Time to publish your product</label>
                            </div>
                          </div>
                          <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                            <button type="submit" class="btn btn-dark btn-lg">Register</button>
                          </div>
                         
                          
                          {{form.errors}}
        
                        
        
                      </div>
                      <div class="col-md-10 col-lg-6 col-xl-7  order-1 order-lg-2" style="margin-top: 200px;">
                        <h3 class="mb-5" style="text-align: center; color: grey;">Choose images for your Product</h3>
                        <div class="d-flex flex-row align-items-center  ">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                              <input class="form-control " type="file" name="image1" accept="image/*" id="id_image1" >
                            <label class="form-label" for="id_profile_picture"></label>
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center  ">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                              <input class="form-control " type="file" name="image2" accept="image/*"  id="id_image2">
                            <label class="form-label" for="id_profile_picture"></label>
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center  ">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                              <input class="form-control " type="file" name="image3" accept="image/*"  id="id_image3">
                            <label class="form-label" for="id_profile_picture"></label>
                          </div>
                        </div>

                        <div class="d-flex flex-row align-items-center  ">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                              <input class="form-control " type="file" name="image3" accept="image/*" id="id_image4">
                            <label class="form-label" for="id_profile_picture"></label>
                          </div>
                        </div>
        
                      </div>
                      
                    </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {% endblock %}
        
</body>
</html>

product/templates/product/deleteconfirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'dashboard/base.html' %}
    {% block content %}
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to remove "{{ object.product }}"?</p>
                <input type="submit" value="Confirm">
        </form>
    {% endblock %}  
</body>
</html>

product/templates/product/editproduct.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'dashboard/base.html' %}
        {% block content %}
        

        {% if product.user == request.user %}
        <section class="vh-100 " style="background-color: grey;">
            <div class="container h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                  <div class="card text-black" style="border-radius: 25px;     margin-bottom: 50px;">
                    <div class="card-body p-md-5">
                      <div class="row justify-content-center">
                        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
          
                          <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Add your Product</p>
  
  
          
                          <form class="mx-1 mx-md-4" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                           
                            <div class="d-flex flex-row align-items-center mb-4">
                              <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                              <div class="form-outline flex-fill mb-0">
                                {{form.name}}
                                <label class="form-label" for="form3Example1c">Product Name</label>
                              </div>
                            </div>
          
                            <div class="d-flex flex-row align-items-center mb-4">
                              <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                              <div class="form-outline flex-fill mb-0">
                                {{form.description}}
                                <label class="form-label" for="form3Example3c">About your productt</label>
                              </div>
                            </div>
  
                            <div class="d-flex flex-row align-items-center mb-4">
                              <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                              <div class="form-outline flex-fill mb-0">
                                {{form.category}}
                                <label class="form-label" for="form3Example3c">Product category</label>
                              </div>
                            </div>
          
                            <div class="d-flex flex-row align-items-center mb-4">
                              <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                              <div class="form-outline flex-fill mb-0">
                                {{form.location}}
                                <label class="form-label" for="form3Example4c">Your location</label>
                              </div>
                            </div>
          
                            <div class="d-flex flex-row align-items-center mb-4">
                              <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                              <div class="form-outline flex-fill mb-0">
                                <input type="number" name="price" value={{form.price.value}} required="" id="id_price" class="form-control">
                                <label class="form-label" for="form3Example4cd">Price of your product</label>
                              </div>
                            </div>
          
                            
                            <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                              <button type="submit" class="btn btn-dark btn-lg">Register</button>
                            </div>
                           
                            
                            {{form.errors}}
          
                          
          
                        </div>
                        <div class="col-md-10 col-lg-6 col-xl-7  order-1 order-lg-2" style="margin-top: 200px;">
                          <h3 class="mb-5" style="text-align: center; color: grey;">Choose images for your Product</h3>
                          <div class="d-flex flex-row align-items-center  ">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                                <!-- <img src={{form.image1.value.url}} alt="image1" style="width: 100px; height: 50px;"> -->
                                <!-- <input class="form-control " type="file" name="image1" accept="image/*" required="" id="id_image1" > -->
                                {{form.image1}}
                                
                              <label class="form-label" for="id_profile_picture"></label>
                            </div>
                          </div>
  
                          <div class="d-flex flex-row align-items-center  ">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              <!-- <img src={{form.image2.value.url}} alt="image2" style="width: 100px; height: 50px;"> -->
                                <!-- <input class="form-control " type="file" name="image2" accept="image/*" required="" id="id_image2"> -->
                                {{form.image2}}
                              <label class="form-label" for="id_profile_picture"></label>
                            </div>
                          </div>
  
                          <div class="d-flex flex-row align-items-center  ">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              <!-- <img src={{form.image3.value.url}} alt="image3" style="width: 100px; height: 50px;"> -->
                                <!-- <input class="form-control " type="file" name="image3" accept="image/*" required="" id="id_image3"> -->
                                {{form.image3}}
                              <label class="form-label" for="id_profile_picture"></label>
                            </div>
                          </div>
  
                          <div class="d-flex flex-row align-items-center  ">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            <div class="form-outline flex-fill mb-0">
                              <!-- <img src={{form.image4.value.url}} alt="image14" style="width: 100px; height: 50px;"> -->
                                <!-- <input class="form-control " type="file" name="image3" accept="image/*" required="" id="id_image4"> -->
                                {{form.image4}}
                              <label class="form-label" for="id_profile_picture"></label>
                            </div>
                          </div>
          
                        </div>
                        
                      </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {% else %}
          <h1>Your are not autherised to do this operation</h1>
          {%endif%}
        
        {% endblock %}
</body>
</html>

product/templates/product/emailnotification.html
{% autoescape off %}

MakeDeal
Product purchase Notification

Hi {{ sellr.username }},
{{buyer.username}} wants to purchase your product {{product}} for Rs {{price}}
{% endautoescape %}

product/templates/product/sellconfirm_mail.html
{% autoescape off %}

MakeDeal
Product purchase Notification

Hi {{ buyer.username }},
{{seller.username}} wants to sell the product {{product}} for your price Rs {{price}}
{% endautoescape %}